# Project
site_name: JeudiDejs de la Tech
site_url: https://lamatkhan.github.io/Mkdocs
repo_url: https://github.com/Lamatkhan/Mkdocs
edit_uri: ""

site_description: 
site_author: Ayana Lamatkhanova
copyright: SixFoisSept 2023

plugins:
- search # un plugin qui permet d'avoir une barre de recherché a
- glightbox # un plugin d'une bibliothèque JavaScript permettant d'implémenter des galeries d'images légères (lightbox) dans une page web.
- badges # un plugin pour insérer les badges dans la doc
- mkdocstrings: # un plugin pour la génération de la documentation API à partir des docstrings
    handlers:
      python: # you can specify python version here
        paths: [src] # mkdocs.yml in root, package in subfolder ( spécifier la structure du projet)
        options: 
          docstring_style: sphinx

# Setup the theme
theme:
  name: 'material'
  logo: 'assets/sixfoissept_logo.png'
  palette:
    primary: violet
    accent: pink
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: en
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - announce.dismiss
    - navigation.tabs

# Add extensions
markdown_extensions:
  tables: # écriture des tables
  attr_list: # The Attribute Lists extension adds a syntax to define attributes on the various HTML elements in markdown’s output.
  md_in_html: # The Markdown in HTML extension allows for writing Markdown inside of HTML, which is useful for wrapping Markdown content with custom elements. 
  admonition:
#  pymdownx.details:
#  pymdownx.extra:
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  pymdownx.inlinehilite:
  pymdownx.snippets:
  pymdownx.highlight:
    use_pygments: true
    linenums: true
  pymdownx.superfences:
    custom_fences:
    - name: mermaid # extension pour la création des diagrammes
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format

# Setup the navbar ( la structure de projet)
nav:
- Home: index.md
- About Us: about.md
- Graphs & Tables: others.md
- API Reference: api.md

# et on peut exclure certains markdowns de la doc
exclude_docs: |
  .*