# Project
site_name: JeudiDejs de la Tech
site_url: https://lamatkhan.github.io/Mkdocs
repo_url: https://github.com/Lamatkhan/Mkdocs
edit_uri: ""

site_description: 
site_author: Ayana Lamatkhanova
copyright: SixFoisSept 2023

plugins:
- search
- glightbox
- mkdocstrings:
    handlers:
      python: # you can specify python version here
        paths: [src] # mkdocs.yml in root, package in subfolder
        options: 
          docstring_style: sphinx

# Setup the navbar
nav:
- Home: index.md
- About Us: about.md
- Graphs & Tables: others.md
- API Reference: api.md


exclude_docs: |
  .*

# Setup the theme
theme:
  name: 'material'
  logo: 'assets/sixfoissept_logo.png'
  palette:
    primary: violet
    accent: pink
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  language: en
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - announce.dismiss
    - navigation.tabs

# Add extensions
markdown_extensions:
  tables:
  attr_list:
  md_in_html:
  admonition:
#  pymdownx.details:
#  pymdownx.extra:
  pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg
  pymdownx.tabbed:
    alternate_style: true
  pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
  pymdownx.inlinehilite:
  pymdownx.snippets:
  pymdownx.highlight:
    use_pygments: true
    linenums: true
  pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format